# compile and run dev build locally
dev:
  nixGLMesa pnpm tauri dev

# reload dev environment
dir:
  direnv reload

# install new dev dependency
i PKG:
	pnpm install -D -- {{PKG}}

# uninstall dependancy
r PKG:
	pnpm rm -- {{PKG}}

# list installed dependancy
l:
	pnpm list

# update
u:
	pnpm update && nix flake update

# build release
b:
	pnpm build

# remove build files generated by `dev`
cc:
  cargo clean --manifest-path src-tauri/Cargo.toml
